baseURL = "https://manuel.is/"
languageCode = "en-us"
title = "manuel.is"
theme = "one"
enableEmoji = true

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
navigation = ["archives.md", "about.md"]
blog = "ramblings"
tagline = "/ˈramblɪŋ/ (of writing or speech) lengthy and confused or inconsequential."
