baseURL = "https://manuel.is/"
languageCode = "en-us"
title = "manuel.is"
theme = "one"
enableEmoji = true

[params]
  navigation = ["archives.md", "about.md"]
  blog = "ramblings"
  tagline = "/ˈramblɪŋ/ (of writing or speech) lengthy and confused or inconsequential."
  siteDescription = "manuel gonzález's (spavi) personal website"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = false
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNumbersInTable = false
    lineNos = true
