baseURL = "https://manuel.is/"
languageCode = "en-us"
title = "manuel.is"
theme = "one"

enableEmoji = true

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
navigation = ["archives.md", "about.md"]
